# Generated by Django 5.1 on 2024-08-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('job_name', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('ordered_by', models.CharField(blank=True, max_length=100)),
                ('ship_to', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
