# Generated by Django 5.1 on 2024-08-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderForm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tempgl1',
            field=models.BooleanField(default=False),
        ),
    ]
