# Generated by Django 5.1 on 2024-08-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderForm', '0003_order_frame_options1_order_glass_options1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='window_type',
            new_name='window_type1',
        ),
    ]
