# Generated by Django 5.1 on 2024-08-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderForm', '0004_rename_window_type_order_window_type1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='height1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='width1',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
