# Generated by Django 5.1 on 2024-08-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderForm', '0009_order_frame_options3_order_frame_options4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='QO',
            field=models.CharField(choices=[('quote', 'Quote'), ('order', 'Order')], default='none', max_length=50),
        ),
    ]
