# Generated by Django 5.1 on 2024-08-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderForm', '0010_order_qo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='signature_field',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
