# Generated by Django 5.1 on 2024-08-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderForm', '0011_order_signature_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='signature_field',
        ),
        migrations.AddField(
            model_name='order',
            name='signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
