# Generated by Django 5.1 on 2024-08-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderForm', '0012_remove_order_signature_field_order_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes5',
            field=models.CharField(max_length=100),
        ),
    ]
