# Generated by Django 5.1 on 2024-09-01 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderForm', '0017_order_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
    ]
