# Generated by Django 5.1 on 2024-09-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderForm', '0018_remove_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Frame_Options10',
            field=models.CharField(blank=True, choices=[('NF', 'Nail Fin'), ('SR', 'Stucco/Retro'), ('B', 'Block')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Frame_Options6',
            field=models.CharField(blank=True, choices=[('NF', 'Nail Fin'), ('SR', 'Stucco/Retro'), ('B', 'Block')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Frame_Options7',
            field=models.CharField(blank=True, choices=[('NF', 'Nail Fin'), ('SR', 'Stucco/Retro'), ('B', 'Block')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Frame_Options8',
            field=models.CharField(blank=True, choices=[('NF', 'Nail Fin'), ('SR', 'Stucco/Retro'), ('B', 'Block')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Frame_Options9',
            field=models.CharField(blank=True, choices=[('NF', 'Nail Fin'), ('SR', 'Stucco/Retro'), ('B', 'Block')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Glass_Options10',
            field=models.CharField(blank=True, choices=[('LE', 'Low-E'), ('GT', 'Grey Tinted'), ('GR', 'Grey Reflective'), ('B', 'Blue')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Glass_Options6',
            field=models.CharField(blank=True, choices=[('LE', 'Low-E'), ('GT', 'Grey Tinted'), ('GR', 'Grey Reflective'), ('B', 'Blue')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Glass_Options7',
            field=models.CharField(blank=True, choices=[('LE', 'Low-E'), ('GT', 'Grey Tinted'), ('GR', 'Grey Reflective'), ('B', 'Blue')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Glass_Options8',
            field=models.CharField(blank=True, choices=[('LE', 'Low-E'), ('GT', 'Grey Tinted'), ('GR', 'Grey Reflective'), ('B', 'Blue')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Glass_Options9',
            field=models.CharField(blank=True, choices=[('LE', 'Low-E'), ('GT', 'Grey Tinted'), ('GR', 'Grey Reflective'), ('B', 'Blue')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Grille_Options10',
            field=models.CharField(blank=True, choices=[('no', 'NA'), ('yes', 'YES')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Grille_Options6',
            field=models.CharField(blank=True, choices=[('no', 'NA'), ('yes', 'YES')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Grille_Options7',
            field=models.CharField(blank=True, choices=[('no', 'NA'), ('yes', 'YES')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Grille_Options8',
            field=models.CharField(blank=True, choices=[('no', 'NA'), ('yes', 'YES')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Grille_Options9',
            field=models.CharField(blank=True, choices=[('no', 'NA'), ('yes', 'YES')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Size_Options10',
            field=models.CharField(blank=True, choices=[('NES', 'Net/Exact Size'), ('RO', 'Rough Opening')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Size_Options6',
            field=models.CharField(blank=True, choices=[('NES', 'Net/Exact Size'), ('RO', 'Rough Opening')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Size_Options7',
            field=models.CharField(blank=True, choices=[('NES', 'Net/Exact Size'), ('RO', 'Rough Opening')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Size_Options8',
            field=models.CharField(blank=True, choices=[('NES', 'Net/Exact Size'), ('RO', 'Rough Opening')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Size_Options9',
            field=models.CharField(blank=True, choices=[('NES', 'Net/Exact Size'), ('RO', 'Rough Opening')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='bnb10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='bnb6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='bnb7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='bnb8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='bnb9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='color10',
            field=models.CharField(blank=True, choices=[('MB', 'Matt Black'), ('MC', 'Matt Chocolate'), ('MDG', 'Matt Dark Grey'), ('MLG', 'Matt Light Grey'), ('CG', 'Champagne'), ('PW', 'Pure White'), ('YW', 'Yellow Wood'), ('GO', 'Golden Oak'), ('YR', 'Yellow Rosewood'), ('RS', 'Red Sandalwood'), ('C', 'Custom')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='color6',
            field=models.CharField(blank=True, choices=[('MB', 'Matt Black'), ('MC', 'Matt Chocolate'), ('MDG', 'Matt Dark Grey'), ('MLG', 'Matt Light Grey'), ('CG', 'Champagne'), ('PW', 'Pure White'), ('YW', 'Yellow Wood'), ('GO', 'Golden Oak'), ('YR', 'Yellow Rosewood'), ('RS', 'Red Sandalwood'), ('C', 'Custom')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='color7',
            field=models.CharField(blank=True, choices=[('MB', 'Matt Black'), ('MC', 'Matt Chocolate'), ('MDG', 'Matt Dark Grey'), ('MLG', 'Matt Light Grey'), ('CG', 'Champagne'), ('PW', 'Pure White'), ('YW', 'Yellow Wood'), ('GO', 'Golden Oak'), ('YR', 'Yellow Rosewood'), ('RS', 'Red Sandalwood'), ('C', 'Custom')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='color8',
            field=models.CharField(blank=True, choices=[('MB', 'Matt Black'), ('MC', 'Matt Chocolate'), ('MDG', 'Matt Dark Grey'), ('MLG', 'Matt Light Grey'), ('CG', 'Champagne'), ('PW', 'Pure White'), ('YW', 'Yellow Wood'), ('GO', 'Golden Oak'), ('YR', 'Yellow Rosewood'), ('RS', 'Red Sandalwood'), ('C', 'Custom')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='color9',
            field=models.CharField(blank=True, choices=[('MB', 'Matt Black'), ('MC', 'Matt Chocolate'), ('MDG', 'Matt Dark Grey'), ('MLG', 'Matt Light Grey'), ('CG', 'Champagne'), ('PW', 'Pure White'), ('YW', 'Yellow Wood'), ('GO', 'Golden Oak'), ('YR', 'Yellow Rosewood'), ('RS', 'Red Sandalwood'), ('C', 'Custom')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='height10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='height6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='height7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='height8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='height9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lh10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='lh6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='lh7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='lh8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='lh9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='notes10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='notes6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='notes7',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='notes8',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='notes9',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rh10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='rh6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='rh7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='rh8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='rh9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tempgl10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tempgl6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tempgl7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tempgl8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tempgl9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='width10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='width6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='width7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='width8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='width9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='window_type10',
            field=models.CharField(choices=[('none', '-- none --'), ('xo_ox', 'XO or OX - 2 Lite Slider X is Active'), ('xox', 'XOX - 3 Lite Slider X is Active'), ('csmt', 'CSMT - Casement'), ('sh', 'SH - Single Hung'), ('pd', 'PD - Patio Door'), ('dh', 'DH - Double Hung'), ('xx', 'XX - 2 Lite (X Active)'), ('pw', 'PW - Picture Window'), ('awn', 'AWN - Awning'), ('fr', 'FR - Swing Door'), ('bf', 'BF - Bifold Window'), ('tt', 'TT - Tilt and Turn'), ('bw', 'BW - Bay Window')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='window_type6',
            field=models.CharField(choices=[('none', '-- none --'), ('xo_ox', 'XO or OX - 2 Lite Slider X is Active'), ('xox', 'XOX - 3 Lite Slider X is Active'), ('csmt', 'CSMT - Casement'), ('sh', 'SH - Single Hung'), ('pd', 'PD - Patio Door'), ('dh', 'DH - Double Hung'), ('xx', 'XX - 2 Lite (X Active)'), ('pw', 'PW - Picture Window'), ('awn', 'AWN - Awning'), ('fr', 'FR - Swing Door'), ('bf', 'BF - Bifold Window'), ('tt', 'TT - Tilt and Turn'), ('bw', 'BW - Bay Window')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='window_type7',
            field=models.CharField(choices=[('none', '-- none --'), ('xo_ox', 'XO or OX - 2 Lite Slider X is Active'), ('xox', 'XOX - 3 Lite Slider X is Active'), ('csmt', 'CSMT - Casement'), ('sh', 'SH - Single Hung'), ('pd', 'PD - Patio Door'), ('dh', 'DH - Double Hung'), ('xx', 'XX - 2 Lite (X Active)'), ('pw', 'PW - Picture Window'), ('awn', 'AWN - Awning'), ('fr', 'FR - Swing Door'), ('bf', 'BF - Bifold Window'), ('tt', 'TT - Tilt and Turn'), ('bw', 'BW - Bay Window')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='window_type8',
            field=models.CharField(choices=[('none', '-- none --'), ('xo_ox', 'XO or OX - 2 Lite Slider X is Active'), ('xox', 'XOX - 3 Lite Slider X is Active'), ('csmt', 'CSMT - Casement'), ('sh', 'SH - Single Hung'), ('pd', 'PD - Patio Door'), ('dh', 'DH - Double Hung'), ('xx', 'XX - 2 Lite (X Active)'), ('pw', 'PW - Picture Window'), ('awn', 'AWN - Awning'), ('fr', 'FR - Swing Door'), ('bf', 'BF - Bifold Window'), ('tt', 'TT - Tilt and Turn'), ('bw', 'BW - Bay Window')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='window_type9',
            field=models.CharField(choices=[('none', '-- none --'), ('xo_ox', 'XO or OX - 2 Lite Slider X is Active'), ('xox', 'XOX - 3 Lite Slider X is Active'), ('csmt', 'CSMT - Casement'), ('sh', 'SH - Single Hung'), ('pd', 'PD - Patio Door'), ('dh', 'DH - Double Hung'), ('xx', 'XX - 2 Lite (X Active)'), ('pw', 'PW - Picture Window'), ('awn', 'AWN - Awning'), ('fr', 'FR - Swing Door'), ('bf', 'BF - Bifold Window'), ('tt', 'TT - Tilt and Turn'), ('bw', 'BW - Bay Window')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes5',
            field=models.CharField(default='', max_length=100),
        ),
    ]
