# Generated by Django 5.1 on 2024-09-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderForm', '0023_orderitem_bnb_orderitem_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
