# Generated by Django 5.1 on 2024-09-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderForm', '0026_order_discount10_order_discount11_order_discount12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(default=list),
        ),
    ]
