# Generated by Django 5.1 on 2024-09-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderForm', '0028_order_extra_discount_order_shipping_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='lh1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lh10',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lh11',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lh12',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lh2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lh3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lh4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lh5',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lh6',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lh7',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lh8',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lh9',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rh1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rh10',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rh11',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rh12',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rh2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rh3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rh4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rh5',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rh6',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rh7',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rh8',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rh9',
        ),
        migrations.AddField(
            model_name='order',
            name='h1',
            field=models.CharField(blank=True, choices=[('lh', 'Left Hand'), ('rh', 'Right Hand')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='h10',
            field=models.CharField(blank=True, choices=[('lh', 'Left Hand'), ('rh', 'Right Hand')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='h11',
            field=models.CharField(blank=True, choices=[('lh', 'Left Hand'), ('rh', 'Right Hand')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='h12',
            field=models.CharField(blank=True, choices=[('lh', 'Left Hand'), ('rh', 'Right Hand')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='h2',
            field=models.CharField(blank=True, choices=[('lh', 'Left Hand'), ('rh', 'Right Hand')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='h3',
            field=models.CharField(blank=True, choices=[('lh', 'Left Hand'), ('rh', 'Right Hand')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='h4',
            field=models.CharField(blank=True, choices=[('lh', 'Left Hand'), ('rh', 'Right Hand')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='h5',
            field=models.CharField(blank=True, choices=[('lh', 'Left Hand'), ('rh', 'Right Hand')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='h6',
            field=models.CharField(blank=True, choices=[('lh', 'Left Hand'), ('rh', 'Right Hand')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='h7',
            field=models.CharField(blank=True, choices=[('lh', 'Left Hand'), ('rh', 'Right Hand')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='h8',
            field=models.CharField(blank=True, choices=[('lh', 'Left Hand'), ('rh', 'Right Hand')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='h9',
            field=models.CharField(blank=True, choices=[('lh', 'Left Hand'), ('rh', 'Right Hand')], max_length=50, null=True),
        ),
    ]
